### ISSUE TITLE
Make seqan3::detail::empty_type public

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#103]
### Description 

Since we use seqan3::detail::empty_type ins some public interfaces it would be good to also put it into seqan3 namespace.

### Acceptance Criteria

- [ ] seqan3::empty_type is a valid type.

### Tasks

 

- [ ] put seqan3::detail::empty_type into seqan3 namespace

**Comment by marehr** [comment]
Resolution 2020-06-08:

We don't make seqan3::detail::empty_type public.

In cases like seqan3::alignment_result, we define the members 

```c++
    constexpr auto id() const noexcept
    {
        static_assert(!has_id, "Identifier is not available but should.");
        // ...
    };
    constexpr auto score() const noexcept;
    constexpr auto const & back_coordinate() const noexcept;
    constexpr auto const & front_coordinate() const noexcept;
    constexpr auto const & alignment() const noexcept;
```

with a return type `auto`.

=> If `!has_id` it is undefined behaviour what `id()` has as a return type.
