### ISSUE TITLE
Post Mortem of unexpected 2x speed-up in minimiser view

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#126]
### Description 

A recent PR seqan/seqan3#1815 was intended as a code cleanup, but ended in an unexpected 2x speed-up for the minimiser view.

Before the change:

```c++
2020-06-12 01:30:08
Running ./view_minimiser_hash_benchmark
compute_minimisers<method_tag::seqan3_ungapped>/50000/8/13      798254 ns       797651 ns          856 Throughput[bp/s]=62.6753M/s
compute_minimisers<method_tag::seqan3_ungapped>/50000/8/28      725392 ns       724750 ns          976 Throughput[bp/s]=68.9797M/s
compute_minimisers<method_tag::seqan3_ungapped>/50000/30/35    2145798 ns      2144391 ns          319 Throughput[bp/s]=23.3031M/s
compute_minimisers<method_tag::seqan3_ungapped>/50000/30/50    2038549 ns      2036937 ns          343 Throughput[bp/s]=24.5324M/s
compute_minimisers<method_tag::seqan3_gapped>/50000/8/13        914172 ns       913483 ns          764 Throughput[bp/s]=54.7279M/s
compute_minimisers<method_tag::seqan3_gapped>/50000/8/28        783494 ns       782962 ns          875 Throughput[bp/s]=63.8512M/s
compute_minimisers<method_tag::seqan3_gapped>/50000/30/35      2238657 ns      2236916 ns          313 Throughput[bp/s]=22.3392M/s
compute_minimisers<method_tag::seqan3_gapped>/50000/30/50      2089251 ns      2087712 ns          332 Throughput[bp/s]=23.9358M/s
```

After the change:

```c++
compute_minimisers<method_tag::seqan3_ungapped>/50000/8/13      482957 ns       482582 ns         1453 Throughput[bp/s]=103.595M/s
compute_minimisers<method_tag::seqan3_ungapped>/50000/8/28      427202 ns       426855 ns         1645 Throughput[bp/s]=117.119M/s
compute_minimisers<method_tag::seqan3_ungapped>/50000/30/35     496929 ns       496523 ns         1402 Throughput[bp/s]=100.642M/s
compute_minimisers<method_tag::seqan3_ungapped>/50000/30/50     433227 ns       432858 ns         1641 Throughput[bp/s]=115.444M/s
compute_minimisers<method_tag::seqan3_gapped>/50000/8/13        946485 ns       945883 ns          723 Throughput[bp/s]=52.8533M/s
compute_minimisers<method_tag::seqan3_gapped>/50000/8/28        873992 ns       873322 ns          793 Throughput[bp/s]=57.2447M/s
compute_minimisers<method_tag::seqan3_gapped>/50000/30/35      2284025 ns      2282055 ns          306 Throughput[bp/s]=21.8974M/s
compute_minimisers<method_tag::seqan3_gapped>/50000/30/50      2181645 ns      2180103 ns          325 Throughput[bp/s]=22.9214M/s
```

So we got 2x speed-up for `seqan3_ungapped` shapes, but about `< 10%` speed-drop for `seqan3_gapped` shapes.

---

The reason for this significant increase was this change:

Before the change:

```c++
    bool next_minimiser()
    {
        std::ranges::advance(window_right, 1);
        if (window_right == urange_end)
            return true;
```

https://github.com/seqan/seqan3/blob/2e0eaafca7021192d8675ce7e265938780f7da07/include/seqan3/range/views/minimiser.hpp#L358-L362

After the change:

```c++
    bool next_minimiser()
    {
        ++urng_iterator;
        if (urng_iterator == urng_sentinel)
            return true;
```

https://github.com/seqan/seqan3/blob/32c1b2e960ce2083c3d89e9e6687d7129a612490/include/seqan3/range/views/minimiser.hpp#L363-L367

But why is there such a difference between `++urng_iterator;` and `std::ranges::advance(window_right, 1);`?!

This benchmarks uses `minimiser_hash`, which is basically the same as `kmer_hash | minimiser`.

So what is the different between `kmer_hash::iterator::operator++` and `std::ranges::advance(kmer_hash::iterator)` for gapped_shapes?

`std::ranges::advance` calls internally `kmer_hash::iterator::operator+=`, which is defined as:

```c++
    shape_iterator & operator+=(difference_type const skip) noexcept
    //!\cond
        requires std::random_access_iterator<it_t>
    //!\endcond
    {
        hash_forward(skip);
        return *this;
    }
```
https://github.com/seqan/seqan3/blob/32c1b2e960ce2083c3d89e9e6687d7129a612490/include/seqan3/range/views/kmer_hash.hpp#L405-L412

```c++
    void hash_forward(difference_type const skip)
    //!\cond
        requires std::random_access_iterator<it_t>
    //!\endcond
    {
        std::ranges::advance(text_left, skip);
        hash_full();
    }
```
https://github.com/seqan/seqan3/blob/32c1b2e960ce2083c3d89e9e6687d7129a612490/include/seqan3/range/views/kmer_hash.hpp#L564-L571

So it does a full hash instead of a rolling hash for ungapped_shapes.

In contrast to `kmer_hash::iterator::operator++`:

```c++
    shape_iterator & operator++() noexcept
    {
        hash_forward();
        return *this;
    }
```
https://github.com/seqan/seqan3/blob/32c1b2e960ce2083c3d89e9e6687d7129a612490/include/seqan3/range/views/kmer_hash.hpp#L363-L367

```c++
    void hash_forward()
    {
        if (shape_.all())
        {
            hash_roll_forward();
        }
        else
        {
            std::ranges::advance(text_left,  1);
            hash_full();
        }
    }
```

https://github.com/seqan/seqan3/blob/32c1b2e960ce2083c3d89e9e6687d7129a612490/include/seqan3/range/views/kmer_hash.hpp#L547-L558

which uses always a rolling hash if it is a ungapped_shape.

----

### So what did we learn?

Never use `std::ranges::advance(it, 1);` use `++it` instead. 

### What can we further interpret from the benchmark timings?

I said in the beginning that we have a 2x speed-up for `seqan3_ungapped` shapes, but about `< 10%` speed-drop for `seqan3_gapped` shapes.

The 2x part is clear, but why do `seqan3_gapped` shapes perform worse when using  `kmer_hash::iterator::operator++` instead of `std::ranges::advance(kmer_hash::iterator)`?

Let's compare the code again:

```c++
    void hash_forward(difference_type const skip)
    //!\cond
        requires std::random_access_iterator<it_t>
    //!\endcond
    {
        std::ranges::advance(text_left, skip);
        hash_full();
    }
```
https://github.com/seqan/seqan3/blob/32c1b2e960ce2083c3d89e9e6687d7129a612490/include/seqan3/range/views/kmer_hash.hpp#L564-L571

```c++
    void hash_forward()
    {
        if (shape_.all())
        {
            hash_roll_forward();
        }
        else
        {
            std::ranges::advance(text_left,  1);
            hash_full();
        }
    }
```

https://github.com/seqan/seqan3/blob/32c1b2e960ce2083c3d89e9e6687d7129a612490/include/seqan3/range/views/kmer_hash.hpp#L547-L558

This `< 10%` speed-drop comes from the additional `if` branch in the hottest-loop in `++`.

This is bad and begs the question why we don't have a static type for ungapped_shapes which enables us the optimisation on the type level and therefore on the view level with constexpr if's?

**Comment by smehringer** [comment]
Nice wrap up :+1:
