### ISSUE TITLE
Provide .gitpod.yml to try out seqan3 in an online editor

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#137]
See https://gitpod.io.

![Screenshot from 2020-02-13 15-05-44](https://user-images.githubusercontent.com/103778/74442760-5bb44300-4e72-11ea-9ad4-c8f45b5160d5.png)

**Comment by eseiler** [comment]
Also see https://github.com/features/codespaces/

**Comment by marehr** [comment]
We advertised browser-supported IDE via #139
