### ISSUE TITLE
Remove `cend` from views, since it is not necessary. `std::ranges::cend()` will call `end` on the const version of the given range .

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#142]
Standard views don't have them: https://eel.is/c++draft/range.transform.view

`std::ranges::cend` does not call `range.cend()`, but `std::as_const(range).end()`: https://eel.is/c++draft/range.access.cend

For Example:

```c++
    //!\copydoc begin()
    auto cbegin() const noexcept
    //!\cond
        requires const_iterable_range<urng_t>
    //!\endcond
    {
        return begin();
    }
```
https://github.com/seqan/seqan3/blob/5831b57a5bcbbf5a03d9ff725d91ca2783a8898b/include/seqan3/range/views/kmer_hash.hpp#L130-L137

and

```c++
    //!\copydoc end()
    auto cend() const noexcept
    //!\cond
        requires const_iterable_range<urng_t>
    //!\endcond
    {
        return end();
    }
    //!\}
```
https://github.com/seqan/seqan3/blob/5831b57a5bcbbf5a03d9ff725d91ca2783a8898b/include/seqan3/range/views/kmer_hash.hpp#L168-L176

Can be removed.

Tasks:
* [ ] Go through all views and remove all `cbegin` and `cend` functions.

---

2020-06-18

Proposal: throw cend / cbegin from views away

Resolution: throw cend / cbegin from views away

**Comment by smehringer** [comment]
Fixed by  seqan/seqan3#1964
