### ISSUE TITLE
Rename view::some_iterator_name to view::[basic_]iterator

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#144]
----

Original Proposal:

### A view should have consistent names for iterator and sentinel types.

I would propose `iterator_type` and `sentinel_type` which should be templatised. Most of our classes already use those names.

The exception to that rule is when the `sentinel_type` is `std::ranges::default_sentinel_t`. In this case `using sentinel_type = std::ranges::default_sentinel_t;`

The standard has only exposition only names for the iterator and sentinel.

* Rene didn't like iterator_type
* We would like the name iterator, sentinel
* There is a name clash with (old) containers and iterator.

----

Resolution 2020-06-08:

* Container have member types `iterator` and `const_iterator` with `basic_iterator<urng [const]>` as iterator base class. (Note: good old containers don't have a sentinel)
* If iterator needs to differentiate constness: `basic_iterator<urng [const]>`; Otherwise name it `iterator`.
* If sentinel  needs to differentiate constness: `basic_sentinel<urng [const]>`; Otherwise name it `sentinel`.

**Comment by eseiler** [comment]
Done
