### ISSUE TITLE
Btw, next time you tag a release please add the `-a` flag. Otherwise git describe uses 3.0.0 as reference.

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#159]
Btw, next time you tag a release please add the `-a` flag. Otherwise git describe uses 3.0.0 as reference.

_Originally posted by @kloetzl in https://github.com/seqan/seqan3/issues/1970#issuecomment-655443725_

**Comment by marehr** [comment]
> Btw, next time you tag a release please add the `-a` flag. Otherwise git describe uses 3.0.0 as reference.

I wrote a support ticket to github, because we created that release with the web interface.

**Comment by rrahn** [comment]
Did you hear something back? So the problem was that the description of the taf was not correct? The `-a` flag is for the annotation right?

**Comment by eseiler** [comment]
Further Reading:

How to tag: https://stackoverflow.com/a/30302668
Why use annotated tags: https://stackoverflow.com/a/4971817
How to show non-annotated (lightweight) tags: https://stackoverflow.com/a/4154518

**Comment by marehr** [comment]
> Did you hear something back? So the problem was that the description of the taf was not correct? The `-a` flag is for the annotation right?

Upps I forgot to post the response here :)

> Steve Graff (GitHub Support)
> 
> Aug 7, 2020, 9:11 PM UTC
> 
> tHi Marcel,
> 
> Thanks for reaching out to GitHub Support. My sincerest apologies for the delay in our response! We appreciate your patience.
> 
> It isn't currently possible to use an annotated tag when creating a release on GitHub.com, but I will forward this as a feature request to our product team for consideration.
> 
> Your ticket was automatically routed to our Developer Support team but our Product team is better suited to help you out. We have forwarded your ticket to the Product team who reads and evaluates all feedback, however we cannot guarantee a response to every submission.
> 
> Please note that this means the Developer Support team will no longer be able to see changes to the ticket, so if you have a follow up that requires further support, please create a new ticket. Thank you again for your feedback!
> 
> Thanks,
> 
> Steve G.
> GitHub Support

**Comment by marehr** [comment]
Just a side note: you can also use `git tag -s 3.0.2`

From the manpage:
> --sign           -s  -- create a signed and annotated tag

**Comment by marehr** [comment]
I used `git tag -s 3.0.2`, so we can close this issue.
