### ISSUE TITLE
UB in kmer_hash_view

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#165]
### Description 

Consider 

```cpp
#include <seqan3/alphabet/nucleotide/dna4.hpp>
#include <seqan3/range/views/kmer_hash.hpp>

int main()
{
    std::vector<seqan3::dna4> text(1);

    auto v = text | seqan3::views::kmer_hash(seqan3::ungapped{2});
    auto it = v.begin();
}
```

The following expressions are UB
```cpp
++it;
it++;
--it;
it--;
it += i; // i != 0
it -= i; // i != 0
```

The iterator should act like a pointer, i.e. pointing somewhere, but for the kmer_hash_view each of these operations actually dereference one (or more) iterators pointing to the text. These iterators may in turn point before the begin / past the end of the underlying range. 
It should be like for a vector - https://godbolt.org/z/oof9nq - moving `it` is fine as long as you do not dereference.

This behaviour is now invoked because we use the `kmer_hash_view` in conjunction with the `std::views::reverse` (minimisers).
At some point (calling `begin()`, calling `empty()`, ...; not on construction though), the reverse_view calls `+=` on the underlying range (here: `kmer_hash_view`) -> UB. **Edit:** This behaviour is fixed by https://github.com/seqan/seqan3/pull/1992

At first glance, I see two solutions:

1: Store begin and end (of the underlying range) when constructing the `kmer_hash_view` and do bounds checking for each of the operations. Just doing the bounds check on construction (current implementation) is not enough.
E.g., `+=` and `-=` could be fixed by a check in `hash_full`:
```cpp
    void hash_full()
    {
        if (text_left >= begin_it && std::ranges::next(text_left, shape_.size()) < end_it)
        {
            text_right = text_left;
            hash_value = 0;


            for (size_t i{0}; i < shape_.size() - 1u; ++i)
            {
                hash_value += shape_[i] * to_rank(*text_right);
                hash_value *= shape_[i] ? sigma : 1;
                std::ranges::advance(text_right, 1);
            }
        }
    }
```

2: Do all the work when dereferencing. Currently, `operator*()` only accesses and dereferences one iterator. There would be to do some checks for what we actually need to compute (full hash, roll forward, ???).

Both approaches will have performance penalty, but the implementation did not seem to be correct to begin with.

### Acceptance Criteria

- [ ] test 1
- [ ] test 2
- [ ] test 3

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
Is this still a problem? @eseiler want to re-evaluate it.

**Comment by eseiler** [comment]
It's still as described, but I don't think it's a problem.

```cpp
    std::vector<seqan3::dna4> text(1);

    auto v = text | seqan3::views::kmer_hash(seqan3::ungapped{2});
    auto it = v.begin();
    ++it;
```

`it` is already at the end, so {de,in}crementing it is UB anyways.

This would be correct:
```cpp
    std::vector<seqan3::dna4> text(1);

    auto v = text | seqan3::views::kmer_hash(seqan3::ungapped{2});
    auto it = v.begin();
    if (it != v.end())
        ++it;
```

**Comment by marehr** [comment]
2021-04-20 Core meeting

The described bug is undefined behaviour. We'll close the issue.

Thank you for the analysis!
