### ISSUE TITLE
Do we want static analysis?

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#187]
https://scan.coverity.com/faq#what-is-coverity-scan

Can be integrated into travis - maybe as nightly?

###### Resolution 10.08.2020

Try it out if it is easy to set up. Don't try to hard if it does not work. If it works make it a nightly job on travis CI.

**Comment by eseiler** [comment]
I tried it.
Unfortunately, they do not support `-fconcepts`/`-std=c++20` (`-std=c++17` is supported).

However, once they support it, the actual process is easy and setting it up in some weekly job should be no problem.

**Comment by eseiler** [comment]
Added to https://github.com/seqan/product_backlog/issues/198
Still no full cpp20 support
