### ISSUE TITLE
Add sequence conversion to cookbook

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#215]
### Description 

We have a `seqan3::views::convert` to, e.g., convert a qualified dna5 vector to a vector without the quality.
But this information is not easily found (cookbook, tutorial, etc.).
I was just lucky to remember that we have a view for this.

There should be a cookbook entry to show common sequence conversions.

### Acceptance Criteria

- [ ] test 1
- [ ] test 2
- [ ] test 3

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by marehr** [comment]
Is this adressed? https://docs.seqan.de/seqan/3-master-user/cookbook.html#cookbook_convert_alphabet_range
