### ISSUE TITLE
Move container, sequence_container, ... into test

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#221]
Follow-up of https://github.com/seqan/seqan3/pull/1898:

What to do with `container`, `sequence_container`,... concept?

----

We want to remove `container`, `sequence_container`, ... from the public API. We might want to reuse those concept in tests so the first step would be to move those concepts to `/test/include/` folder.

**Comment by smehringer** [comment]
We are using the concepts in the library, e.g. `sequence_container`

They moved to utility/concept.hpp and it seems that this is what was inteneded [here](https://github.com/seqan/seqan3/wiki/Core-Meeting-notes#2019-12-09-rrahn) but with the original names.

So this is outdated
