### ISSUE TITLE
Use -D_GLIBCXX_ASSERTIONS in our CI builds

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#231]
### Description 

https://github.com/seqan/seqan3/issues/2209 showed us that we have code with undefined behaviour.

`-D_GLIBCXX_ASSERTIONS` would be an extra hardening flag to catch those errors:

> _GLIBCXX_ASSERTIONS
>
>    Undefined by default. When defined, enables extra error checking in the form of precondition assertions, such as bounds checking in strings and null pointer checks when dereferencing smart pointers. 

https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html

We might also consider to use `_GLIBCXX_DEBUG`:

> _GLIBCXX_DEBUG
>
>    Undefined by default. When defined, compiles user code using the debug mode. When defined, _GLIBCXX_ASSERTIONS is defined automatically, so all the assertions enabled by that macro are also enabled in debug mode. 

### Acceptance Criteria

- [ ] test 1
- [ ] test 2
- [ ] test 3

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by eseiler** [comment]
We are using this flag in our nightlies https://cdash.seqan.de/index.php?project=SeqAn3#!#Experimental
