### ISSUE TITLE
!!! Finalise sequence and container concepts

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#240]
### Description 

Revisit the concepts for containers that are based on the container requirements described in https://en.cppreference.com/w/cpp/named_req. The problem is that the container concepts are in many cases not really helpful to be used in generic contexts. This topic is more exhaustively described within the thesis of @h-2.
One intermediate solution was presented here:
    * Move container, sequence_container, ... into test https://github.com/seqan/product_backlog/issues/221
It suggests to put them first into test for internal use.

related:

* rename `reservible_container` to `reservable_container` (typo everywhere)

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>

**Comment by smehringer** [comment]
See https://github.com/seqan/product_backlog/issues/221
