### ISSUE TITLE
! Cleanup the debug stream include

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#243]
### Description

* Get `seqan3::debug_stream` straight once and for all: https://github.com/seqan/product_backlog/issues/63
* move debug_stream_alphabet into `alphabet/concept.hpp`, because core should not depend on alphabet.
* debug_stream and fmtflags2 still falsely appear as part of I/O module (they are part of core now)

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>

**Comment by eseiler** [comment]
Resolved
