### ISSUE TITLE
Additional package resource

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#253]
### Description

I use conan package manager, which is the sate-of-the art package manager specifically for C++ resources. I resolve all my dependencies through conan and would like to also resolve my application dependencies to SeqAn3 in a one-package-management solution.

related:

* SeqAn3 can be installed via conan package manager.
* A recipe exists that describes how to add a SeqAn application to conan package manager.

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>

**Comment by eseiler** [comment]
Done
