### ISSUE TITLE
!!! Compiler support

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#255]
### Description

Add support for gcc-11 and clang-11 to check if our current understanding and usage of modern features such as concepts is indeed working and stable. If something breaks and the solution might have an effect on the public API, then we cannot make a reliable stable release as resolving it would introduce API breaks later.

related

* all tests, snippets, benchmarks and applications based on SeqAn 3 build through and run successfully when compiled with g++-11 or clang-11. 
* the output is as expected and is not effected by different rules established by the compilers.

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>

**Comment by smehringer** [comment]
We have gcc-11. gcc-12 and clang are tracked in #402 and #127
