### ISSUE TITLE
!!! Stable dependencies

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#256]
### Description

Publish stable releases for our external dependencies: cereal, sdsl3 and SeqAn2, so that starting with SeqAn 3.1 release we can ship with these dependencies and also package SeqAn3 as a stand alone library.

related:

* SeqAn 2.5 is released and can coexist with SeqAn3. Specifically, I can upgrade my SeqAn2 program and use algorithms from SeqAn3 to replace steps in my current program. The other way around will be not supported. This means we can't assume that SeqAn3 data structures will work in SeqAn2 algorithms.
* The sdsl 3.0 is released and shipped by the supported package vendors. For this we need a stable EPR dictionary. What else? There are still some open problems that might affect the construction of indices and other. Do they have an effect on the interfaces?
* Cereal is released and stable and can be used within our data structures reliably and foreseeable in the future as long as we run in SeqAn3 mode. -> Optimally, we can exchange the serialisation mechanism in the backend without affecting the public API of our algorithms.
* c++20 will be released at the end of 2020 and is then fix. So we need to make sure to be fully compliant with any small changes that might happen in the meantime.

### Tasks

<details><summary>Definition of Done</summary>
<p>

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

</p>
</details>

**Comment by smehringer** [comment]
Core Meeting 25.10.2021 : We will tag the SDSL with a release in the current state.

**Comment by smehringer** [comment]
Core Meeting 01.11.2021 : We will tag SeqAn2 with a release 2.5 in the current state.
