### ISSUE TITLE
[MISC] Rename/Move of add_enum_bitwise_operations

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#260]
### Description 

* Remove the `add_enum_bitwise_operators` from the public API documentation using `//!\cond DEV`
* Document the bitwise functionality in each enum that uses  `add_enum_bitwise_operators`
  * In the same file, create an `interface` in doxygen (`\interface`, examples in codebase) called `enum_bitwise_operators`
  * Document out enums that use `add_enum_bitwise_operators` with `\implements`

Public enums should be:
* `seqan3::fmtflags2`
* `seqan3::sam_flag`
* `seqan3::translation_frames`

----
## Discussion

Current implementation: https://godbolt.org/z/EfPP7e
Move into detail: https://godbolt.org/z/nW4b6e

In both scenarios, `using seqan3::operator|;`  inside the detail namespace or `using seqan3:::detail::operator|` inside the seqan namespace will make it work.
That means, we can make it detail and just pull it into the seqan namespace.

And for some detail stuff:
* `seqan3::detail::trace_directions`
* `seqan3::detail::strong_type_skill`

We can do the same for strong_type, but it is already detail.

**Comment by rrahn** [comment]
### Core meeting 2020-11-23

We will keep the version that overloads the seqan3 namespace because it is just simpler and less error prone.
We try out documenting the operators as part of a doxygen interface description, which can then be added to a enum that implements these operators.
