### ISSUE TITLE
Remove seqan3::views::persist

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#307]
Does the view::persist models pointer semantics similar to the ref_view of the standard or not: https://github.com/seqan/seqan3/pull/1964

----

Resolution 2020-07-13:

The general feeling is that `seqan3::views::persist` is more misused than it brings benefit. The long-term goal should be to deprecate it and remove it.

`seqan3::views::persist` is not a view, because it is not deconstructible in constant time. (The standard changed this last minute)

* [x] `seqan3::views::persist` should be deep-const (done by wiep) Was this done???
* [x] Make `seqan3::views::persist` detail. (short-term)
* [ ] Offer `seqan3::views::persist` with a deprecation warning
* [ ] (This means we don't use `seqan3::views::persist` internally any more)
* [ ] Walk-through all usages of `seqan3::views::persist` and try to remove them. (long-term)

**Comment by marehr** [comment]
First part is done, we made it private.

**Comment by eseiler** [comment]
https://github.com/seqan/product_backlog/issues/416
