### ISSUE TITLE
de.NBI / cibi User Meeting 2021

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#308]
### Description 

* [ ] User Meeting: 13.09.2021 - 17.09.2021
* [ ] Website: https://www.denbi.de/training/1283-cibi-user-meeting-2021
* [ ] Schedule: https://ogy.de/ts51

**Comment by eaasna** [comment]
Might be nice to mention in the tutorial that there is an app template

**Comment by marehr** [comment]
simple fm-index in tutorial: short introduction what a read-mapper does; especially what a fm-index solves.

Provide a skeleton with a seqan3::argument_parser.
