### ISSUE TITLE
GCB 2021, September 08, 2pm

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#309]
### Description 

* [x] GCB 2021: 6. September - 9. September
* [x] GCB 2021: Wednesday, September 08, 2021, 2 pm
* [x] 16. August um 10 Uhr (Monday); Test-Presentation
* [x] 18. August um 14 Uhr (Wednesday). Test-Presentation

Test-Presentation:
https://us02web.zoom.us/j/86259132251?pwd=YXJhTUsrdmtFR1hBYWlXVW84aGRLUT09

**Comment by marehr** [comment]
### Presenters

**René Rahn**, Max Planck Institute for Molecular Genetics, Algorithmic Bioinformatics, Germany
**Marcel Ehrhardt**, Free University Berlin, Algorithmic Bioinformatics, Germany
**Enrico Seiler**, Max Planck Institute for Molecular Genetics, Algorithmic Bioinformatics, Germany

### Overview

In this half-day tutorial we are going to teach how to use modern C++ and utilise efficient C++ libraries to rapidly develop tools and scripts for operating on and manipulating large-scale sequencing data.

### Motivation

The high variability and heterogeneity often observed within various genomic data is challenging for many standard tools, for example for read alignment and variant calling. Often, these tools are wrapped in complicated pre- and postprocessing data curation steps in order to obtain results with higher quality. However, these additional steps incur a high maintenance and performance burden to the established work process and often do not scale with larger data sets. Seldomly, C++ is considered as the language of choice for these small processes, although it is the main language used in high-performance computing. We are going to show that implementing modern C++ can be as easy as using other modern high-level languages.

### Course outline:

This tutorial is organised as a half-day tutorial. At the beginning we are going to introduce fundamental concepts and principles of the C++ programming language. Further, we will teach how modern C++ features such as ranges and concepts can be used to rapidly develop high-quality C++ applications. This introduction to C++ follows a practical session where participants will read in typical files from sequencing experiments using the C++ library SeqAn and operate on the data with the taught principles to solve diverse problems, e.g. filtering out reads with low sequencing quality and others. In the last 30 minutes of the day we are going to summarise the learned concepts and compare the developed methods to current approaches.

### Intended audience and level:

This tutorial is mostly suited for computational biologist and bioinformaticians with research focus on sequence analysis (e.g., genomics, metagenomics, proteomics, read alignment, variant detection, etc.). A fundamental knowledge about sequencing experiments and the involved data is required. We expect that attendees have an intermediate knowledge in programming with any high-level programming language, e.g. Python, Java or C++. Some basic C++-knowledge is helpful but not mandatory to successfully complete the course.

This tutorial is targeting beginners and intermediate C++ developers that want to learn more about modern C++ features like ranges and concepts.

### Learning Objectives:

Students will develop

* skills in developing an application using the C++ programming language
* knowledge and understanding of modern C++ features, such as ranges and concepts
* knowledge and understanding about how to develop and sustain high-quality software

### Requirements:

Attendees should bring their own laptop.
Software for the tutorial can be installed beforehand, but we will also dedicate some extra time for installing required software during the tutorial.

    Git
    g++ >= 7
    SeqAn 3 - (https://github.com/seqan/seqan3)
    CMake >= 3.12

or, VirtualBox if the attendee wishes to use the provided virtual image running Ubuntu.

**Maximum Attendees: 25**

### Schedule Overview

You want a peek at our preliminary Presentation? [No Problem!][1]

[1]: https://seqan.github.io/learning-resources/doc/biocpp/presentation/#/

time | content
-- | --
9:00 - 9:30 am | Introduction to modern C++ [talk: 30 min]
9:30 - 10:30 am | Initial app and parsing sequencing data [hands-on: 60 min]
10:30 - 11:00 am | Break
11:00 - 12:30 pm | Filtering and data manipulation [hands-on: 90 min]
12:30 - 1:00 pm | Wrap-up [talk: 30 min]

**Comment by marehr** [comment]
> Lieber Herr Ehrhardt,
> 
> wir haben Ihren Workshop für den Termin
> 	Mittwoch, 08. September 2021, 14 Uhr
> vorgesehen und diesen Termin nun auch in die Workshop-Liste unter https://gcb2021.de/Workshops.html aufgenommen, was in Kürze sichtbar werden sollte.
> Anbei finden Sie Präsentationsfolien für die Einführung in das Konferenzsystem, die von der Dechema durchgeführt wird. Testläufe sind geplant für den 16. und 18. August 2021.
> 
> Abhängig vom Format Ihres Workshops können in der ZOOM-Konferenz während des Workshops unterschiedliche Einstellungen gewählt werden, insbesondere im Hinblick auf die Möglichkeit für Teilnehmer*innen Kamera und Bildschirm zu teilen.
> Daher möchten wir Sie bitten, uns mitzuteilen, ob Ihr Workshop eher als ein Tutorial mit Präsentation vornehmlich durch die Organisator*innen oder als eine interaktive Sitzung, bei der auch Teilnehmer*innen den Bildschirm teilen können, abgehalten werden soll.
> 
> Mit freundlichen Grüßen
> 
> 	Jan Grau


[Guidelines workshop organizer_GCB 2021.pdf](https://github.com/seqan/product_backlog/files/6836615/Guidelines.workshop.organizer_GCB.2021.pdf)

* am 16. August um 10 Uhr und
* am 18. August um 14 Uhr.

**Comment by marehr** [comment]
Lieber Herr Ehrhardt,

leider hatte Herr Grau die E-Mail etwas zu spät versandt und ich war gestern aufgrund der Schuleinführung meines Sohnes nicht im Büro.

Ihr Workshop auf der GCB 2021 wird in folgendem Zoom-Raum stattfinden, es ist ein anderer Raum, als der des Testlaufs:
https://us02web.zoom.us/j/87238834421?pwd=a2kwdGs2a0kwQzNiZW9zSUF3U0FOQT09
Meeting-ID: 872 3883 4421 Kenncode: 231904

Der Raum ist heute bis 15:30 und morgen ab 12.30 Uhr zum Testen verfügbar.

Bitte entschuldigen Sie die Verwirrung.

Herzliche Grüße
Kristina

**Comment by smehringer** [comment]
Done
