### ISSUE TITLE
clean up nigthlies of BER

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#367]
**All builds in Debug mode unless otherwise noted.**

### GCC versioned
* gcc-9 `-std=c++17 -fconcepts` (Release)
* gcc-10 `-std=c++20 -fsanitize=address`
* gcc-10 `-std=c++20 -fsanitize=undefined`

### GCC trunk
* gcc-9-git `-std=c++17 -fconcepts`
* gcc-9-git `-std=c++2a`
* gcc-10-git `-std=c++20`
* gcc-11-git `-std=c++20`
* gcc-git `-std=c++20`

## header
* gcc-9 `-std=c++17 -fconcepts` (Release)
* gcc-9 `-std=c++17 -fconcepts`
* gcc-10 `-std=c++20` (Release)
* gcc-10 `-std=c++20`
* use gcc-11 instead of 10 when available

## documentation
* doxygen-git

## experimental
* gcc-9 `-std=c++17 -fconcepts -D_GLIBCXX_USE_CXX11_ABI=0` (Release)

**Comment by eseiler** [comment]
Done
