### ISSUE TITLE
Use a generalised binning directory where a technical bin itself is not a bin with sequences but itself is a technical binning directory subsuming multiple smaller technical bins

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#37]
### Description 

When too many bins are too small, they can be joind in one technical binning directory and used inside a balanaced binning directory. This avoids wasted space for too small bins.

### Acceptance Criteria

- [ ] test 1
- [ ] test 2
- [ ] test 3

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by smehringer** [comment]
Done in https://github.com/seqan/chopper
