### ISSUE TITLE
Make add_enum_bitwise_operators a private entity

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#390]
### Description 

- [ ] Remove the `add_enum_bitwise_operators` from the public API documentation using `//cond DEV`
- [ ] Document the bitwise functionality in each enum that uses  `add_enum_bitwise_operators`
- [ ] Pull `add_enum_bitwise_operators` into the detail namespace such that it works for enums that are declared in the detail namespace
 
- [ ] Do the same for strong types!

----

> We decided to make `add_enum_bitwise_operators`'s documentation private (`\\!cond DEV`) and document related enums (`\copydoc`?, `\relates`?, TBD). [Card1](https://github.com/orgs/seqan/projects/4#card-32890520), [Card2](https://github.com/seqan/seqan3/projects/19#card-33218933)

See Resolution of [Core-Meeting 2020-02-17](https://github.com/seqan/seqan3/wiki/Core-Meeting-notes#2020-02-17-eseiler)

**Comment by eseiler** [comment]
https://github.com/seqan/seqan3/pull/2323
