### ISSUE TITLE
Add constexpr to char literals creating a vector

### ISSUE THREAD

**Issue by eseiler** [seqan/product_backlog#399]
The only thing I want to add is that we should also add `constexpr` to
```cpp
inline aa10li_vector operator""_aa10li(char const * const s, size_t const n)
```
if the compiler supports `constexpr std::vector`. 

But this should be another PR in any case.

_Originally posted by @eseiler in https://github.com/seqan/seqan3/issues/2819#issuecomment-925592163_

---

@eseiler Good point!

_Originally posted by @marehr in https://github.com/seqan/seqan3/issues/2819#issuecomment-925598614_

---

> @eseiler Good point!

We could probably do something like this

```cpp
#if defined(__cpp_lib_constexpr_vector) && __cpp_lib_constexpr_vector >= 201907L
#    define SEQAN3_CHAR_LITERAL_VECTOR constexpr
#else
#    define SEQAN3_CHAR_LITERAL_VECTOR inline
#endif
```

However, only MSVC implements `constexpr` for `std::vector`.

https://godbolt.org/z/EKGxYnEas

_Originally posted by @eseiler in https://github.com/seqan/seqan3/issues/2819#issuecomment-925619276_

**Comment by marehr** [comment]
As constexpr is a best effort declaration in the sense that in doubt it won't compile, we could simply declare it constexpr without any macros.

**Comment by eseiler** [comment]
> As constexpr is a best effort declaration in the sense that in doubt it won't compile, we could simply declare it constexpr without any macros.

But the function body still needs to be a valid, (possibly) constant expression. And because we construct the vector inside the literal, it doesn't work.

https://godbolt.org/z/394KTozjc

**Comment by marehr** [comment]
Thank you, I thought it would just work, but you right :(
