### ISSUE TITLE
Alphabet Module

### ISSUE THREAD

**Issue by remyschwab** [seqan/product_backlog#404]
* [x] [alphabet_rank_t](https://docs.seqan.de/seqan/3-master-user/group__alphabet.html#ga553a1ffc22a1e6fbc8bcd81bdefac630) is missing the api stability tag (https://github.com/seqan/seqan3/pull/2855)

Part of #393

**Comment by smehringer** [comment]
Fixed by https://github.com/seqan/seqan3/pull/2855
