### ISSUE TITLE
translation TODOs

### ISSUE THREAD

**Issue by h-2** [seqan/product_backlog#407]
seqan/seqan3#56 has been merged, but there are some open issues that should be addressed before the first SeqAn3 release:
  - [x] benchmark against seqan2 code
  - [x] consider writing a dedicated `view_translation` to get better performance
  - [x] turn the tests into TYPED_TEST so that a single test can test all the nucl-alphabets

For release:
  - [x] store view instead of shared_ptr
  - [x] rename `translation.hpp` → `translate.hpp`
  - [x]  add `\includeheader` to mark which header provides the view.
  - [x] add non-const member functions and non-const iterator

Nice-to-have:
  - [x] view_translate_join (multiframe 2d → 2d)
  - [x] benchmark (#1371)

Outline
  - when the use case arises, implement other translation tables
  - should translation table be a run-time choice, too? Right now it is only compile_time; benchmark compile-time influence

**Comment by smehringer** [comment]
We will not implement new translation tables or make the translation table be a run-time choice without a use case. 

Once the use case arises, no information from here are actually valuable to tackle it, so this issue can be seen as resolved given the other tasks.
