### ISSUE TITLE
Rename enable_safe_range to enable_borrowed_range.

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#48]
The current standard has renamed `enable_safe_range` to `enable_borrowed_range` and `safe_range` to `borrowed_range`.

* [x] Wait until ranges v3 renamed the names.

> Remarks: Pursuant to [namespace.std], users may specialize enable_­borrowed_­range for cv-unqualified program-defined types.
Such specializations shall be usable in constant expressions ([expr.const]) and have type `const bool`.
[ Example: Each specialization S of class template subrange ([range.subrange]) models borrowed_-range because
    `enable_­borrowed_­range<S>` is specialized to have the value true, and
    S's iterators do not have validity tied to the lifetime of an S object because they are “borrowed” from some other range.
— end example
 ]

https://eel.is/c++draft/range.req#range.range-itemdecl:3

Depends on
* [x] https://github.com/ericniebler/range-v3/pull/1501

**Comment by rrahn** [comment]
resolved by seqan/seqan3#2014
