### ISSUE TITLE
Factory-Pattern in Algorithms

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#52]
Proposals:
* https://godbolt.org/z/fYeCH- (std::enable_view style with one builder class that offers all possible ways to construct with search results explicit fields in search results by marcel)
  <details>
  <summary>Click to expand!</summary>
  Dieses Design-pattern würde das entkoppeln: [https://godbolt.org/z/fYeCH-](https://godbolt.org/z/fYeCH-).Eine base class anzugeben ist derzeit auch der Weg in der Standard Library bestimmtes Verhalten generischen Klassen zu geben. Z.b. `std::ranges::enable_view` schaut, ob man von einer view_base erbt und wenn ja, dann kann die Klasse neue Sachen oder hat bestimmte Eigenschaften. In seqan3 bräuchten wir kein eigenes `std::ranges::enable_view` Konstrukt und könnten einfach immer erwarten, dass eine (Äquivalenz-)Klasse von Algorithmen, z.B. in diesem Beispiel eine Suche oder ein Alignment, von einer common-base class erbt. Das macht es auch einfach für andere (externe) Personen neue Such oder Alignment Algorithmen zu programieren und in unser allgemeines Such-Interface oder Alignment-Interface zu integrieren.
  </details>
* https://godbolt.org/z/mFrxa4 (over policy system and/or tuple in search results by rene)
* (one builder class that offers all possible ways to search results and explicit fields in search results instead of tuple by svenja)

To vote (bold vote won) :
* **policy-based** (rene) vs base-class (marcel), vs builder class (svenja)
* search result gets as constructor std::tuple and one member (rene) vs has **explicit members and explicit constructor arguments** (svenja, marcel)
* search result has one template argument (rene) vs a lot of **template arguments** (marcel)

**Comment by rrahn** [comment]
Is implemented now for search and alignment.
