### ISSUE TITLE
Get `seqan3::debug_stream` straight once and for all.

### ISSUE THREAD

**Issue by marehr** [seqan/product_backlog#63]
### Description 

As a developer / user I want that the `seqan3::debug_stream` is as lightweight as possible so that I debug sections of my code without pulling the complete library in and making my problem worst.

Some properties of debug_stream:
1) value of a type can only be printed if the type was defined before
2) It must have an order to know which printer it should use to print. This should be done at a single place.
3) The definition of a debug_stream overload should be cheap. (It should not include more headers)
4) The definition of a debug_stream overload should be local to what it overloads to.

We currently have the following issues:

* including `seqan3/core/debug_stream.hpp` includes
  * `seqan3/alignment/aligned_sequence/aligned_sequence_concept.hpp` (pulls in alignment stuff)
  * `seqan3/core/detail/debug_stream_alphabet.hpp` (should only be defined if any alphabet is included; pulls in mask alphabet)
  * `seqan3/core/detail/debug_stream_optional.hpp` (pulls in `std::optional`: we could forward declare everything, because of property (1) this would work )
  * `seqan3/core/detail/debug_stream_range.hpp` (pulls in alphabet concept, char and uint adaptation) This uses the terminology of "sequences" (see #60) and prints a `std::vector<char>` as it was a `std::string`. Pulls in complete `seqan3/std/ranges`. Not sure if we somehow can forward declare this. The ranges library has forward header, we should definitely add a `seqan3/std/ranges_fwd.hpp` header. We should assume that the `<ranges>` header is stable and works properly.
  * `seqan3/core/detail/debug_stream_tuple.hpp` (could be forward declared; pulls also tuple_like concept in; pulls in alphabets and ranges?!; put generic debug_stream overload in `seqan3/core/concept/tuple.hpp`?)
  * `seqan3/core/detail/debug_stream_type.hpp` (this defines unused features like an own flag definition which make the design much more complicated)
  * `seqan3/core/detail/debug_stream_variant.hpp` (could be forward declared)
*  including `seqan3/core/to_string.hpp` includes `seqan3/core/debug_stream.hpp` (see problems above)
*  including `seqan3/test/pretty_printing.hpp` includes `seqan3/core/debug_stream.hpp` (see problems above)
* We can't select (internally) what we want to debug print, for example a range or a sequence. This is critical if you want to print values where you know of which kind they are
* It is hard to know which overload resolution is used and we sometimes need to pull in more headers to exclude other overloads even if we don't need them. For example `seqan3/core/detail/debug_stream_tuple.hpp` pulls in the "completely" related alphabets and ranges in to resolve an ambiguous overload an alphabet_tuple and a more generic tuple.
* `debug_stream` accepts anything, but can't handle everything; big oof `debug_stream << unknown_type{};` (this is also not SFINAE friendly, because syntactically from the signature debug_stream allows any type but it might not be able to handle it) If we accept anything, then we should also compile for everything and give a runtime exception if an overload is missing.
* We can't differentiate if a `debug_stream` overload comes from us or if it comes from `std::ostream`. This would be handy for googletest overload of `PrintTo`.
* Overloading `<<` has the same issues as for `std::ostream`! A HUUUGGGGH stack trace. These overloads should be kept to a absolutely minimum.
* All these dependencies make it really hard to add support new compilers and platforms since every little thing can break and if every test includes `seqan3/test/pretty_print.hpp` it basically pulls in half of our library which makes it extremely hard to find the issue.
* It also breaks the idea that a unit test is the smallest possible subset to test a functionality.
* We should only include in tests the debug_stream overloads that we need. (If a test does not need ranges, we should not include it)

### Acceptance Criteria

- [ ] test 1
- [ ] test 2
- [ ] test 3

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by rrahn** [comment]
### Team resolution:

* Make a backlog item with gist design proposal (discuss with two other people core and newbie)
* more information: https://github.com/seqan/seqan3/wiki/Core-Meeting-notes#2020-05-11-marehr
* debug_stream should not give hard compiler errors if a overload is missing; it should accept every type and throw an exception that it does not support the type.

**Comment by smehringer** [comment]
FMPOV this is done
