### ISSUE TITLE
Add support for clang-tidy

### ISSUE THREAD

**Issue by rrahn** [seqan/product_backlog#7]
### Acceptance Criteria

- [ ] test

### Tasks

- [ ] task

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

**Comment by eseiler** [comment]
Tracked in https://github.com/seqan/product_backlog/issues/425
