### ISSUE TITLE
Underscores in test and test suite names

### ISSUE THREAD

**Issue by joergi-w** [seqan/product_backlog#76]
In SeqAn3 and in the app template (therefore in all future SeqAn3 applications) we use test and test suite names in snake case style, containing a lot of underscores.

However, according to the [Googletest documentation](https://github.com/google/googletest/blob/master/googletest/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore) the use of underscores in the middle of test and test suite names is generally not recommended and as first or last characters they are forbidden. This is because the names are internally chained with underscores, which can lead to ambiguous class names and other compiler errors (for details please see the linked document). The main statement of Gtest is:

> If you violate the rule, there may not be immediate consequences, but your test may (just may) break with a new compiler (or a new version of the compiler you are using) or with a new version of googletest. Therefore it's best to follow the rule.

I received different opinions from @marehr and @smehringer when I pointed this out, so it seems necessary to discuss whether we take action.

In my opinion we need to consider the following questions:
1. In the Library Coding Guide we state that variables, classes, concepts, functions etc. should be snake case. Would we want to violate this for test names? 
2. Do test names actually belong to one of the elements above or are they rather macros and can be styled differently? Note, that we do not use these names anywhere again, they really just define the test identity.
3. Currently, everything works and it would be much effort to change everything. Can we wait until it may break after an update etc. and take action only then (in the hope it does not happen)?
4. Is a change of the test names an API break, which we do not allow after a certain release any more? If yes, this could get us into a dilemma later.
5. Is it a good idea to use CamelCase style for test and test suite names anyway, in order to emphasize that the `TEST` and `TEST_F` lines are Googletest macros and not SeqAn library code?

**Comment by smehringer** [comment]
Core Meeting 25.10.2021 - We will tackle this once it becomes an actual issue. We will directly see if tests fail when we update a compiler or the google test version.
