### ISSUE TITLE
[doc] value parameter in arg-parser is in-out, not out

### ISSUE THREAD

**Issue by h-2** [seqan/product_backlog#81]
The `value` parameter in the argument parser is specified as being an out-parameter when it actually is an in-out parameter (previous value is considered default).

Also `validator` is used both as concept and as local variable name which is quite confusing.

**Comment by h-2** [comment]
> Can you give an example or the line of code that fails / is unexpected?

https://github.com/seqan/seqan3/blob/master/include/seqan3/argument_parser/argument_parser.hpp#L222
https://github.com/seqan/seqan3/blob/master/include/seqan3/argument_parser/argument_parser.hpp#L255
https://github.com/seqan/seqan3/blob/master/include/seqan3/argument_parser/argument_parser.hpp#L283

> What would you expect?

It should be marked `[in,out]`. I am pretty sure @smehringer knows what I mean.

**Comment by rrahn** [comment]
But it does not help if a single person understands this. The entire team must understand the ticket. If only ever a single person understands the meaning then there is no transparency and no knowledge transfer. If the sinlge person is not available or around the ticket becomes useless. So a littlebit more context like the follow-up comment would be very appreciated. 😄
